<?php return array (
  0 => 
  array (
    'source' => 'Version',
    'trans' => 'Version',
  ),
  1 => 
  array (
    'source' => 'Dernière mise à jour',
    'trans' => 'Last update',
  ),
  2 => 
  array (
    'source' => 'Tous les contenus sont générés par l\'auteur du site, mais proviennent des livres des Ombres d\'Esteren,<br />et appartiennent au collectif Forgesonges, et édité par Agate Editions.',
    'trans' => 'All contents are generated by the author, but come from Shadows of Esteren books,<br /> and belong to the Forgesonges association, books are edited by Agate Editions (Studio 2 Publishing in the US).',
  ),
  3 => 
  array (
    'source' => 'Page générée en',
    'trans' => 'Page generated in',
  ),
  4 => 
  array (
    'source' => 'millisecondes',
    'trans' => 'milliseconds',
  ),
  5 => 
  array (
    'source' => 'Tous droits réservés - Pierstoval',
    'trans' => 'All rights reserved - Pierstoval',
  ),
);