services:
    php:
        build:
            context: ./docker/php/
        working_dir: /srv/
        volumes: ["./:/srv"]

    caddy:
        build:
            context: ./docker/caddy/
        working_dir: /srv/
        volumes: ["./:/srv/"]
        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp"

    mailcatcher:
        image: mailhog/mailhog

    database:
        image: 'mysql:5.7'
        volumes:
            - './docker/mysql/:/app/'
        environment:
            - MYSQL_DATABASE=corahnrin
            - MYSQL_ROOT_PASSWORD=corahnrin
